$(document).ready(function(){
$(".img5").hover(function(){
    $(".img1").hide(1);
    $(".img2").show(1);
    $(".img3").hide(1);
    $(".img4").hide(1);
})
$(".img6").hover(function(){
    $(".img1").hide(1);
    $(".img2").hide(1);
    $(".img3").show(1);
    $(".img4").hide(1);
})
$(".img7").hover(function(){
    $(".img1").hide(1);
    $(".img2").hide(1);
    $(".img3").hide(1);
    $(".img4").show(1);
})
})